spring:
  application:
    name: weblibrary
  jpa:
    generate-ddl: off  # "off" для отмены авто-генерации БД через "JPA"
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        ddl-auto: validate
  liquibase:
    enabled: on
    change-log: classpath:db/changelog/weblibrary-db-master.xml

app:
  datasource:
    weblibrary:
      driver-class-name: org.postgresql.Driver
      url: jdbc:postgresql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME:weblibrary}?currentSchema=public
      username: ${DATABASE_USER}
      password: ${DATABASE_PASSWORD}


logging:
  level:
    org:
      hibernate:
        SQL: ERROR
      type:
        descriptor:
          sql:
            BasicBinder: ERROR
      springframework:
        jdbc:
          core:
            JdbcTemplate: ERROR
            StatementCreatorUtils: ERROR

springdoc:
  packagesToScan: com.example.weblibrary
  swagger-ui:
    disable-swagger-default-url: true
