server:
  port: 8085
spring:
  jpa:
    generate-ddl: off  # "off" для отмены авто-генерации БД через "JPA"
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
  liquibase:
    enabled: on
    change-log: classpath:db/changelog/weblibrary-db-master.xml

app:
  datasource:
    weblibrary:
      driver-class-name: org.postgresql.Driver
      url: jdbc:postgresql://localhost:5432/weblibrary
      username: postgres
      password: post@post23
